server:
  port: 8080
spring:
  application:
    name: ParkingTime
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingtime
    username: testuser
    password: ivan3214
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: office.ratify@gmail.com
    password: kgoncyuqaohznkkz
    port: 587
    host: smtp.gmail.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enabled: true
  packagesToScan: "com.parkingtime"